SET search_path = public, pg_catalog;

-- Data for table public.system_country
INSERT INTO tbl_system_country
(id, name, code)
VALUES
(1, 'Afghanistan', 'AF'),
(2, 'Åland Islands', 'AX'),
(3, 'Albania', 'AL'),
(4, 'Algeria', 'DZ'),
(5, 'American Samoa', 'AS'),
(6, 'Andorra', 'AD'),
(7, 'Angola', 'AO'),
(8, 'Anguilla', 'AI'),
(9, 'Antarctica', 'AQ'),
(10, 'Antigua and Barbuda', 'AG'),
(11, 'Argentina', 'AR'),
(12, 'Armenia', 'AM'),
(13, 'Aruba', 'AW'),
(14, 'Australia', 'AU'),
(15, 'Austria', 'AT'),
(16, 'Azerbaijan', 'AZ'),
(17, 'Bahamas', 'BS'),
(18, 'Bahrain', 'BH'),
(19, 'Bangladesh', 'BD'),
(20, 'Barbados', 'BB'),
(21, 'Belarus', 'BY'),
(22, 'Belgium', 'BE'),
(23, 'Belize', 'BZ'),
(24, 'Benin', 'BJ'),
(25, 'Bermuda', 'BM'),
(26, 'Bhutan', 'BT'),
(27, 'Bolivia', 'BO'),
(28, 'Bosnia and Herzegovina', 'BA'),
(29, 'Botswana', 'BW'),
(30, 'Bouvet Island', 'BV'),
(31, 'Brazil', 'BR'),
(32, 'British Indian Ocean Territory', 'IO'),
(33, 'Brunei Darussalam', 'BN'),
(34, 'Bulgaria', 'BG'),
(35, 'Burkina Faso', 'BF'),
(36, 'Burundi', 'BI'),
(37, 'Cambodia', 'KH'),
(38, 'Cameroon', 'CM'),
(39, 'Canada', 'CA'),
(40, 'Cape Verde', 'CV'),
(41, 'Caribbean Netherlands ', 'BQ'),
(42, 'Cayman Islands', 'KY'),
(43, 'Central African Republic', 'CF'),
(44, 'Chad', 'TD'),
(45, 'Chile', 'CL'),
(46, 'China', 'CN'),
(47, 'Christmas Island', 'CX'),
(48, 'Cocos (Keeling) Islands', 'CC'),
(49, 'Colombia', 'CO'),
(50, 'Comoros', 'KM'),
(51, 'Congo', 'CG'),
(52, 'Congo, Democratic Republic of', 'CD'),
(53, 'Cook Islands', 'CK'),
(54, 'Costa Rica', 'CR'),
(55, 'Côte d''Ivoire', 'CI'),
(56, 'Croatia', 'HR'),
(57, 'Cuba', 'CU'),
(58, 'Curaçao', 'CW'),
(59, 'Cyprus', 'CY'),
(60, 'Czech Republic', 'CZ'),
(61, 'Denmark', 'DK'),
(62, 'Djibouti', 'DJ'),
(63, 'Dominica', 'DM'),
(64, 'Dominican Republic', 'DO'),
(65, 'Ecuador', 'EC'),
(66, 'Egypt', 'EG'),
(67, 'El Salvador', 'SV'),
(68, 'Equatorial Guinea', 'GQ'),
(69, 'Eritrea', 'ER'),
(70, 'Estonia', 'EE'),
(71, 'Ethiopia', 'ET'),
(72, 'Falkland Islands', 'FK'),
(73, 'Faroe Islands', 'FO'),
(74, 'Fiji', 'FJ'),
(75, 'Finland', 'FI'),
(76, 'France', 'FR'),
(77, 'French Guiana', 'GF'),
(78, 'French Polynesia', 'PF'),
(79, 'French Southern Territories', 'TF'),
(80, 'Gabon', 'GA'),
(81, 'Gambia', 'GM'),
(82, 'Georgia', 'GE'),
(83, 'Germany', 'DE'),
(84, 'Ghana', 'GH'),
(85, 'Gibraltar', 'GI'),
(86, 'Greece', 'GR'),
(87, 'Greenland', 'GL'),
(88, 'Grenada', 'GD'),
(89, 'Guadeloupe', 'GP'),
(90, 'Guam', 'GU'),
(91, 'Guatemala', 'GT'),
(92, 'Guernsey', 'GG'),
(93, 'Guinea', 'GN'),
(94, 'Guinea-Bissau', 'GW'),
(95, 'Guyana', 'GY'),
(96, 'Haiti', 'HT'),
(97, 'Heard and McDonald Islands', 'HM'),
(98, 'Honduras', 'HN'),
(99, 'Hong Kong', 'HK'),
(100, 'Hungary', 'HU'),
(101, 'Iceland', 'IS'),
(102, 'India', 'IN'),
(103, 'Indonesia', 'ID'),
(104, 'Iran', 'IR'),
(105, 'Iraq', 'IQ'),
(106, 'Ireland', 'IE'),
(107, 'Isle of Man', 'IM'),
(108, 'Israel', 'IL'),
(109, 'Italy', 'IT'),
(110, 'Jamaica', 'JM'),
(111, 'Japan', 'JP'),
(112, 'Jersey', 'JE'),
(113, 'Jordan', 'JO'),
(114, 'Kazakhstan', 'KZ'),
(115, 'Kenya', 'KE'),
(116, 'Kiribati', 'KI'),
(117, 'Kuwait', 'KW'),
(118, 'Kyrgyzstan', 'KG'),
(119, 'Lao People''s Democratic Republic', 'LA'),
(120, 'Latvia', 'LV'),
(121, 'Lebanon', 'LB'),
(122, 'Lesotho', 'LS'),
(123, 'Liberia', 'LR'),
(124, 'Libya', 'LY'),
(125, 'Liechtenstein', 'LI'),
(126, 'Lithuania', 'LT'),
(127, 'Luxembourg', 'LU'),
(128, 'Macau', 'MO'),
(129, 'Macedonia', 'MK'),
(130, 'Madagascar', 'MG'),
(131, 'Malawi', 'MW'),
(132, 'Malaysia', 'MY'),
(133, 'Maldives', 'MV'),
(134, 'Mali', 'ML'),
(135, 'Malta', 'MT'),
(136, 'Marshall Islands', 'MH'),
(137, 'Martinique', 'MQ'),
(138, 'Mauritania', 'MR'),
(139, 'Mauritius', 'MU'),
(140, 'Mayotte', 'YT'),
(141, 'Mexico', 'MX'),
(142, 'Micronesia, Federated States of', 'FM'),
(143, 'Moldova', 'MD'),
(144, 'Monaco', 'MC'),
(145, 'Mongolia', 'MN'),
(146, 'Montenegro', 'ME'),
(147, 'Montserrat', 'MS'),
(148, 'Morocco', 'MA'),
(149, 'Mozambique', 'MZ'),
(150, 'Myanmar', 'MM'),
(151, 'Namibia', 'NA'),
(152, 'Nauru', 'NR'),
(153, 'Nepal', 'NP'),
(154, 'New Caledonia', 'NC'),
(155, 'New Zealand', 'NZ'),
(156, 'Nicaragua', 'NI'),
(157, 'Niger', 'NE'),
(158, 'Nigeria', 'NG'),
(159, 'Niue', 'NU'),
(160, 'Norfolk Island', 'NF'),
(161, 'North Korea', 'KP'),
(162, 'Northern Mariana Islands', 'MP'),
(163, 'Norway', 'NO'),
(164, 'Oman', 'OM'),
(165, 'Pakistan', 'PK'),
(166, 'Palau', 'PW'),
(167, 'Palestine, State of', 'PS'),
(168, 'Panama', 'PA'),
(169, 'Papua New Guinea', 'PG'),
(170, 'Paraguay', 'PY'),
(171, 'Peru', 'PE'),
(172, 'Philippines', 'PH'),
(173, 'Pitcairn', 'PN'),
(174, 'Poland', 'PL'),
(175, 'Portugal', 'PT'),
(176, 'Puerto Rico', 'PR'),
(177, 'Qatar', 'QA'),
(178, 'Réunion', 'RE'),
(179, 'Romania', 'RO'),
(180, 'Russian Federation', 'RU'),
(181, 'Rwanda', 'RW'),
(182, 'Saint Barthélemy', 'BL'),
(183, 'Saint Helena', 'SH'),
(184, 'Saint Kitts and Nevis', 'KN'),
(185, 'Saint Lucia', 'LC'),
(186, 'Saint Vincent and the Grenadines', 'VC'),
(187, 'Saint-Martin (France)', 'MF'),
(188, 'Samoa', 'WS'),
(189, 'San Marino', 'SM'),
(190, 'Sao Tome and Principe', 'ST'),
(191, 'Saudi Arabia', 'SA'),
(192, 'Senegal', 'SN'),
(193, 'Serbia', 'RS'),
(194, 'Seychelles', 'SC'),
(195, 'Sierra Leone', 'SL'),
(196, 'Singapore', 'SG'),
(197, 'Sint Maarten (Dutch part)', 'SX'),
(198, 'Slovakia', 'SK'),
(199, 'Slovenia', 'SI'),
(200, 'Solomon Islands', 'SB'),
(201, 'Somalia', 'SO'),
(202, 'South Africa', 'ZA'),
(203, 'South Georgia and the South Sandwich Islands', 'GS'),
(204, 'South Korea', 'KR'),
(205, 'South Sudan', 'SS'),
(206, 'Spain', 'ES'),
(207, 'Sri Lanka', 'LK'),
(208, 'St. Pierre and Miquelon', 'PM'),
(209, 'Sudan', 'SD'),
(210, 'Suriname', 'SR'),
(211, 'Svalbard and Jan Mayen Islands', 'SJ'),
(212, 'Swaziland', 'SZ'),
(213, 'Sweden', 'SE'),
(214, 'Switzerland', 'CH'),
(215, 'Syria', 'SY'),
(216, 'Taiwan', 'TW'),
(217, 'Tajikistan', 'TJ'),
(218, 'Tanzania', 'TZ'),
(219, 'Thailand', 'TH'),
(220, 'The Netherlands', 'NL'),
(221, 'Timor-Leste', 'TL'),
(222, 'Togo', 'TG'),
(223, 'Tokelau', 'TK'),
(224, 'Tonga', 'TO'),
(225, 'Trinidad and Tobago', 'TT'),
(226, 'Tunisia', 'TN'),
(227, 'Turkey', 'TR'),
(228, 'Turkmenistan', 'TM'),
(229, 'Turks and Caicos Islands', 'TC'),
(230, 'Tuvalu', 'TV'),
(231, 'Uganda', 'UG'),
(232, 'Ukraine', 'UA'),
(233, 'United Arab Emirates', 'AE'),
(234, 'United Kingdom', 'GB'),
(235, 'United States', 'US'),
(236, 'United States Minor Outlying Islands', 'UM'),
(237, 'Uruguay', 'UY'),
(238, 'Uzbekistan', 'UZ'),
(239, 'Vanuatu', 'VU'),
(240, 'Vatican', 'VA'),
(241, 'Venezuela', 'VE'),
(242, 'Vietnam', 'VN'),
(243, 'Virgin Islands (British)', 'VG'),
(244, 'Virgin Islands (U.S.)', 'VI'),
(245, 'Wallis and Futuna Islands', 'WF'),
(246, 'Western Sahara', 'EH'),
(247, 'Yemen', 'YE'),
(248, 'Zambia', 'ZM'),
(249, 'Zimbabwe', 'ZW')
;
